### PR TITLE
Add Nobis pellet stove to README

### PR DESCRIPTION
**Pull request by CBK482**
customer code : 700700
url : https://nobis.agua-iot.com

### CODE REVIEW

**Comment by miguelpissarra** [comment]
How did you get that customer code and url api?
I need to get that information for Cadel pellet stove.

**Comment by CBK482** [comment]
Hey Miguel,

 

Since android 11, it’s not so easy anymore to use a “man in the middle” approach since installing a root certificate to decrypt is not possible anymore.

In the end, I managed to use the android emulator from android Studio. You need to use a non Play Store enabled image, otherwise the same restrictions apply on the emulator (https://httptoolkit.tech/blog/inspect-any-android-apps-http/)

 

Without playstore you need to install the app using adb istall command, but that’s also explained in the link.

 

Good luck

**Comment by thetux07** [comment]
hello,
i have a nobis pellet stove, but i can't connect it, you have good connect your stove ?
thank you

**Comment by CBK482** [comment]
Hey Frederic,

 

My stove is down for the moment, but I just tried and at least I can connect to the service and get the list of my stoves (Only one 😉 )

Since my stove is down, I can’t ask it for information, but since you’re not actually connecting to the stove (it’s the stove that connects to the service) I think there should be no issue

**Comment by Daarrz** [comment]
Hello, i have a Nobis stove too and after installing Micronova Agua IOT i'm getting the following error whe i try to put the url/customer code : 

User input malformed: expected str for dictionary value @ data['brand_id']

Can you help me please ? thx

**Comment by angeloniclaudio** [comment]
Daarz, just delete the content of field Brand Id and re-write the value 1.
It will fix the unexpected issue.

**Comment by Daarrz** [comment]
Hello, works fine but now I have the following issue :

Logger: homeassistant.components.climate
Source: custom_components/aguaiot/climate.py:164
Integration: Thermostat (documentation, issues)
First occurred: 8 février 2023 à 21:25:41 (16 occurrences)
Last logged: 09:28:04

Error adding entities for domain climate with platform aguaiot
Error while setting up aguaiot platform for climate
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 442, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 717, in _async_add_entity
    await entity.add_to_platform_finish()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 814, in add_to_platform_finish
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 566, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 609, in _async_write_ha_state
    attr.update(self.state_attributes or {})
  File "/usr/src/homeassistant/homeassistant/components/climate/__init__.py", line 297, in state_attributes
    self.current_temperature,
  File "/config/custom_components/aguaiot/climate.py", line 164, in current_temperature
    return self._device.air_temperature
  File "/usr/local/lib/python3.10/site-packages/py_agua_iot/__init__.py", line 583, in air_temperature
    return float(self.__get_information_item('temp_air_get'))
  File "/usr/local/lib/python3.10/site-packages/py_agua_iot/__init__.py", line 430, in __get_information_item
    formula = self.__register_map_dict[item]['formula']
KeyError: 'temp_air_get'


Do you have any idea ? Thx best regards

**Comment by thetux07** [comment]
hello 
yes 
take my fork
https://github.com/thetux07/py-agua-iot

**Comment by Daarrz** [comment]
Hello, thx por your anwser but i'm getting the same logs : 

> Logger: homeassistant.components.climate
> Source: custom_components/aguaiot/climate.py:164
> Integration: Thermostat (documentation, issues)
> First occurred: 15:27:43 (2 occurrences)
> Last logged: 15:27:43
> 
> Error adding entities for domain climate with platform aguaiot
> Error while setting up aguaiot platform for climate
> Traceback (most recent call last):
>   File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 442, in async_add_entities
>     await asyncio.gather(*tasks)
>   File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 717, in _async_add_entity
>     await entity.add_to_platform_finish()
>   File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 814, in add_to_platform_finish
>     self.async_write_ha_state()
>   File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 566, in async_write_ha_state
>     self._async_write_ha_state()
>   File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 609, in _async_write_ha_state
>     attr.update(self.state_attributes or {})
>   File "/usr/src/homeassistant/homeassistant/components/climate/__init__.py", line 297, in state_attributes
>     self.current_temperature,
>   File "/config/custom_components/aguaiot/climate.py", line 164, in current_temperature
>     return self._device.air_temperature
>   File "/usr/local/lib/python3.10/site-packages/py_agua_iot/__init__.py", line 583, in air_temperature
>     return float(self.__get_information_item('temp_air_get'))
>   File "/usr/local/lib/python3.10/site-packages/py_agua_iot/__init__.py", line 430, in __get_information_item
>     formula = self.__register_map_dict[item]['formula']
> KeyError: 'temp_air_get'


I'm stuck :s

**Comment by thetux07** [comment]
the problem it's with nobis is not temp_air_get but is temp-air2_get

https://github.com/fredericvl/py-agua-iot/issues/34

i have fork and modify 

it work great now

**Comment by Daarrz** [comment]
I'm using your fork aswell : 

image
image
image

**Comment by thetux07** [comment]
Ok tu es français ça va être plus facile pour moi :-)
Je pense qu’il reprend le py de l’ancien dépôt il faudrait que tu désinstalle, redémarre complètement ton host et réinstaller mon fork ça devrait fonctionner

**Comment by Daarrz** [comment]
Ça fonctionne toujours pas, on peut se retrouver sur discord ? Daarz#6684

**Comment by vincentwolsink** [comment]
Already included via other PR.

**Pull request closed without merging**
